In [2]:
import numpy as np
import pandas as pd
import sympy

In [3]:
A = np.array([[2, 0, 2, 0], [1, 1, 1, 1], [0, 0, 3, 2], [1, 0, 0, 5]])
A

array([[2, 0, 2, 0],
       [1, 1, 1, 1],
       [0, 0, 3, 2],
       [1, 0, 0, 5]])

In [39]:
def det(A):
    assert A.shape[0] == A.shape[1]

    if A.shape == (2, 2):
        solution = f"({A[0, 0]})({A[1, 1]}) - ({A[0, 1]})({A[1, 0]})"
        return A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0], solution
    
    solution = ""
    det_value = 0
    
    for i in range(A.shape[1]):
        sign = 1 if i % 2 == 0 else -1
        sign_str = "-" if sign == -1 else "+"
        
        if A[0, i] != 0:
            sub_matrix = np.c_[A[1:, 0:i], A[1:, i+1:]]
            sub_det, sub_solution = det(sub_matrix)
            solution += f"{sign_str}({A[0, i]})({sub_solution})"
            det_value += sign * A[0, i] * sub_det
            
    
    return det_value, solution
        
    

In [40]:
A[0:0].size

0

In [42]:
det(A)

(34,
 '+(2)(+(1)((3)(5) - (2)(0))-(1)((0)(5) - (2)(0))+(1)((0)(0) - (3)(0)))+(2)(+(1)((0)(5) - (2)(0))-(1)((0)(5) - (2)(1))+(1)((0)(0) - (0)(1)))')

In [38]:
A[1:, 1:]

array([[1, 1, 1],
       [0, 3, 2],
       [0, 0, 5]])

In [45]:
np.linalg.det(np.eye(3))

1.0

In [46]:
np.linalg.det(5 * np.eye(3))

124.99999999999994

In [47]:
5 * np.eye(3)

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [48]:
np.linalg.det([[2, 4, 2, 6], [3, 3, 27, 33], [2, 1, 5, 2], [6, 1, -3, 3]])

3317.999999999996

In [49]:
2 * np.linalg.det([[2, 4, 2, 6], [1, 1, 2, 0], [2, 1, 5, 2], [6, 1, -3, 3]]) + np.linalg.det([[2, 4, 2, 6], [1, 1, 23, 33], [2, 1, 5, 2], [6, 1, -3, 3]])

3317.9999999999977

In [50]:
np.linalg.det([[2, 4, 2, 6], [3, 3, 7, 8], [2, 1, 5, 2], [6, 1, -3, 3]])

358.0

In [51]:
(4*np.linalg.det([[3, 7, 8], [2, 5, 2], [6, -3, 3]])
-3 * np.linalg.det([[2, 2, 6], [2, 5, 2], [6, -3, 3]])
+ np.linalg.det([[2, 2, 6], [3, 7, 8], [6, -3, 3]])
 - np.linalg.det([[2, 2, 6], [3, 7, 8], [2, 5, 2]]))

-358.00000000000045