In [17]:
import numpy as np
import sympy

import string

In [30]:
a = np.array([
    [1, 0, 1/3, 0, 3],
    [0, 1, -2/3, 0, -1],
    [0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0]
])

In [49]:
def show_solutions(rref_matrix):

        def solution_format(solution):
            return solution
        
        def get_freevars(num_freevars):
            freevars = []
            iterator = iter(string.ascii_lowercase)
            for _ in range(num_freevars):
                freevars.append(sympy.sympify(next(iterator)))
            return freevars
            

        solution = {
            'inconsistent': False,
            'type': None, # line, plane, hyperplane
            'param_vecs': []
        }


        for row in range(rref_matrix.shape[0]):
            if rref_matrix[row, :-2].sum() == 0 and rref_matrix[row, -1] != 0:
                solution['inconsistent'] = True
                return solution_format(solution)


        pivots = []
        i = 0
        j = 0
        while i < rref_matrix.shape[0] and j < rref_matrix.shape[1] - 1:
            if rref_matrix[i, j] == 0:
                j += 1
            else:
                pivots.append((i, j))
                j += 1
                i += 1

        num_freevars = rref_matrix.shape[1] - len(pivots) - 1
        
        cols = rref_matrix.shape[1] - 1
        
        if num_freevars == 0:
            solution['type'] = 'Point'
            
            vec = np.zeros(shape=(cols,))
            for row in range(min(rref_matrix.shape[0], cols)):
                vec[row] = rref_matrix[row, -1]
            solution['param_vecs'].append(vec)
            
            return solution_format(solution)
    

        freevars_cols = []
        for col in range(rref_matrix.shape[1] - 1):
            is_pivot = False
            for pivot in pivots:
                if pivot[1] == col:
                    is_pivot = True
                    break
                elif pivot[1] > col:
                    break
            
            if not is_pivot:
                freevars_cols.append(col)
                
        
        assert len(freevars_cols) == num_freevars
        
        for col in freevars_cols:
            vec = np.zeros(shape=(cols,), dtype=)
            
            for row in range(rref_matrix.shape[0]):
                vec[row] = -rref_matrix[row, col]
                
            vec[col] = 1
            solution['param_vecs'].append(vec)
            
        vec = np.zeros(shape=(cols,))
        for row in range(min(rref_matrix.shape[0], cols)):
            vec[row] = rref_matrix[row, -1]
        solution['param_vecs'].append(vec)
        
        if len(freevars_cols) == 1:
            solution['type'] = 'Line'
        elif len(freevars) == 2:
            solution['type'] = 'Plane'
        else:
            solution['type'] = 'Hyperplane'
            
        return solution_format(solution)
        
        
    

In [50]:
show_solutions(a)

{'inconsistent': False,
 'param_vecs': [array([-0.33333333,  0.66666667,  1.        , -0.        ]),
  array([ 3., -1.,  0.,  0.])],
 'type': 'Line'}

In [51]:
a

array([[ 1.        ,  0.        ,  0.33333333,  0.        ,  3.        ],
       [ 0.        ,  1.        , -0.66666667,  0.        , -1.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

In [53]:
a[1, :-1]

array([ 0.        ,  1.        , -0.66666667,  0.        ])

In [56]:
np.all(a[-1, :-1] == 0)

True